name: TestingPlugin
version: '${project.version}'
main: com.ethnicthv.testingplugin.TestingPlugin
api-version: 1.19
depend: [ ProtocolLib ]
commands:
  test:
    description: a Test command
  datalist:
    description: a Data command